##
## Copyright (C) 2025 Dremio Corporation
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    name: Build & Publish
    timeout-minutes: 30
    permissions:
      contents: read

    steps:

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # The setup-gradle action fails, if the wrapper is not using the right version or is not present.
          # Our `gradlew` validates the integrity of the `gradle-wrapper.jar`, so it's safe to disable this.
          validate-wrappers: false

      - name: Gradle Build & Publish
        run: |
          ./gradlew --continue --scan build publish -x intTest -x longTest

      - name: Gradle OAuth2 Core Integration Tests
        run: |
          ./gradlew --continue --scan :authmgr-oauth2-core:intTest

      - name: Gradle Check Generated Docs
        run: |
          ./gradlew --no-scan generateDocs
          git diff --exit-code docs/configuration.md
          if [ $? -ne 0 ]; then
            echo "Generated documentation does not match existing documentation. Please run './gradlew generateDocs' and commit the changes."
            exit 1
          fi

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-test-results
          path: |
            **/build/test-results/**

  long-tests:

    runs-on: ubuntu-latest
    name: Long Running Tests
    permissions:
      contents: read

    steps:

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: false

      - name: Gradle OAuth2 Core Long Tests
        run: |
          ./gradlew --continue --scan :authmgr-oauth2-core:longTest -Dauthmgr.it.long.total=PT1M

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: long-tests-results
          path: |
            **/build/test-results/**

  spark-tests:

    runs-on: ubuntu-latest
    name: Spark Tests
    permissions:
      contents: read

    steps:

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: false

      - name: Gradle Run Spark Tests
        run: |
          ./gradlew --continue --scan \
            :authmgr-oauth2-runtime-spark-tests:printTestMatrix \
            :authmgr-oauth2-runtime-spark-tests:intTestMatrix

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: spark-tests-results
          path: |
            **/build/test-results/**

  flink-tests:

    runs-on: ubuntu-latest
    name: Flink Tests
    permissions:
      contents: read

    steps:

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: false

      - name: Gradle Run Flink Tests
        run: |
          ./gradlew --continue --scan \
            :authmgr-oauth2-runtime-flink-tests:printTestMatrix \
            :authmgr-oauth2-runtime-flink-tests:intTestMatrix

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: flink-tests-results
          path: |
            **/build/test-results/**
